### ISSUE TITLE
error: target not found: plasma-wayland-session

### ISSUE THREAD

**Issue by JungerBoyo** [dreemurrs-embedded/arch-pine64-build#17]
When running script as such:
```
sudo ./build.sh -a aarch64 -d pinetab2 -u plasma_desktop
```
During the second-phase following error occurs:
```
error: target not found: plasma-wayland-session
ERROR: Failed to run the second phase rootfs build!
```
Command `sudo ./build.sh -a aarch64 -d pinetab2 -u sxmo` succeeds btw.

**Comment by Danct12** [comment]
Fixed in e02535d446657457a5f47780c62040a35bf6f52c
